services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_DB=portfoliodb'
      - 'POSTGRES_PASSWORD=p0rtf0l10'
      - 'POSTGRES_USER=portfolio'
    ports:
      - '5432:5432'

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@portfolio.dev'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres

