server:
  port: 19480
  address: 0.0.0.0
  servlet:
    context-path: /portfoliotracker

spring:
  application:
    name: MyPortFolioTracker
  task:
    scheduling:
      pool:
        size: 4
  datasource:
    url: jdbc:postgresql://db.agtkcnxmlbccbwmsuxdz.supabase.co:6543/postgres?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${SUPABASE_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${supabase.jwt.jwks-uri}

logging:
  level:
    org.springframework.security: DEBUG
    com.sro.myportfoliotracker.config: DEBUG
#telegram:
#  bot-token: 8740857212:AAGLNpT9xtpcHFd5xE8YfaKUiqNw3zjYv8k
#  chat-id: "156014286"
#  enabled: true

supabase:
  jwt:
    jwks-uri: https://agtkcnxmlbccbwmsuxdz.supabase.co/auth/v1/.well-known/jwks.json
