server:
  port: 19480
  address: 0.0.0.0
  servlet:
    context-path: /portfoliotracker

spring:
  application:
    name: MyPortFolioTracker
  datasource:
    url: jdbc:sqlite:./data/portfolio.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
#telegram:
#  bot-token: 8740857212:AAGLNpT9xtpcHFd5xE8YfaKUiqNw3zjYv8k
#  chat-id: "156014286"
#  enabled: true

