server:
  port: 19480
  address: 0.0.0.0
  servlet:
    context-path: /portfoliotracker

spring:
  application:
    name: MyPortFolioTracker
  profiles:
    default: standalone
  task:
    scheduling:
      pool:
        size: 4
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${supabase.jwt.jwks-uri}

logging:
  level:
    org.springframework.security: DEBUG
    com.sro.myportfoliotracker.config: DEBUG

supabase:
  jwt:
    jwks-uri: https://agtkcnxmlbccbwmsuxdz.supabase.co/auth/v1/.well-known/jwks.json
